# Generated by Django 3.1.2 on 2026-05-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='published',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tad',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(fields=('article', 'tag'), name='unique_scope'),
        ),
    ]
